# name: NYC Day Care
pygments: true
baseurl: /NYCdaycare

markdown: redcarpet
pygments: true

title_tag_text: Daycare Map NYC
h1_tag_text: Daycare Map NYC

exclude: ["README.md", "CNAME"]

# exclude: ["Procfile", "Gruntfile.js", "README.md", "package.json", "CNAME", "node_modules"]
