# name: NYC Day Care
pygments: true
baseurl: /NYCdaycare

markdown: redcarpet
pygments: true

title_tag_text: NYC Day Care
h1_tag_text: NYC Day Care

exclude: ["Procfile", "README.md", "CNAME"]

# exclude: ["Gruntfile.js", "package.json", "node_modules"]
